[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 55422
shadow_port = 55420
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true

[inbucket]
enabled = true
port = 55424
smtp_port = 55425
pop3_port = 55426

[storage]
enabled = true
file_size_limit = "50MiB"

[analytics]
enabled = false
