[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  # Prevent Netlify secret scanner from blocking builds for legitimate environment variables
  # These variables are either public (NEXT_PUBLIC_*) or necessary for server-side functionality
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_APP_URL,NEXT_PUBLIC_SITE_URL,APP_BASE_URL,SUPABASE_SERVICE_ROLE_KEY,GOOGLE_CLIENT_ID"
  # Omit build output paths where environment variables are legitimately embedded
  SECRETS_SCAN_OMIT_PATHS = ".next/**,netlify/**,.netlify/**,src/mocks/data/briefingData.ts,src/services/email/templateRenderer.ts,supabase/config.toml,supabase/migrations/**"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.googleusercontent.com https://*.gstatic.com https://www.google-analytics.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.googleapis.com https://*.supabase.co https://*.supabase.in; frame-src 'self' https://accounts.google.com;"
